// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_200_points = "CgkIyfOGx4MJEAIQAw"; // <GPGSID>
        public const string achievement_100_points = "CgkIyfOGx4MJEAIQAg"; // <GPGSID>
        public const string achievement_750_points = "CgkIyfOGx4MJEAIQBw"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIyfOGx4MJEAIQAQ"; // <GPGSID>
        public const string achievement_300_points = "CgkIyfOGx4MJEAIQBA"; // <GPGSID>
        public const string achievement_400_points = "CgkIyfOGx4MJEAIQBQ"; // <GPGSID>
        public const string achievement_1000_points = "CgkIyfOGx4MJEAIQCA"; // <GPGSID>
        public const string achievement_500_points = "CgkIyfOGx4MJEAIQBg"; // <GPGSID>

}

